Repository maistra/maistra.github.io, pull requests merged in 2020-04, with the labels that each got.

#113 Improve formatting in Installation Options
  topics/docs/installation/installation-options.adoc
Labels: okay to merge

#109 MAISTRA-1079: Replace deprecated Kubernetes API's
  topics/docs/installation/automatic-injection.adoc
Labels: okay to merge

#111 MAISTRA-1160 Add documentation on how to use an existing Jaeger instance
  topics/docs/installation/installation-options.adoc
  topics/docs/monitoring_and_tracing/using-existing-jaeger.adoc
Labels: okay to merge

#114 Add Logo
  themes/hugo-theme-learn-master/layouts/partials/logo.html
Labels: okay to merge

#115 [maistra-1323] [maistra-904] Updated for Maistra-1.1
  config.toml
  topics/contribute/index.adoc
  topics/docs/comparison-with-istio/_index.adoc
  topics/docs/comparison-with-istio/ior.adoc
  topics/docs/examples/bookinfo.adoc
  topics/docs/examples/mesh-wide_mtls.adoc
  topics/docs/examples/mesh-wide_rbac.adoc
  topics/docs/installation/311-nodes.adoc
  topics/docs/installation/application-requirements.adoc
  topics/docs/installation/automatic-injection.adoc
  topics/docs/installation/configuring-members.adoc
  topics/docs/installation/controlplane-templates.adoc
  topics/docs/installation/controlplane.adoc
  topics/docs/installation/installation-options.adoc
  topics/docs/installation/operator-installation.adoc
  topics/docs/monitoring_and_tracing/grafana.adoc
  topics/docs/monitoring_and_tracing/jaeger-tracing.adoc
  topics/docs/monitoring_and_tracing/kiali.adoc
  topics/docs/monitoring_and_tracing/prometheus.adoc
  topics/docs/monitoring_and_tracing/using-existing-jaeger.adoc
  topics/docs/troubleshooting/must_gather.adoc
  topics/docs/troubleshooting/troubleshooting_policy.adoc
  topics/docs/troubleshooting/troubleshooting_sidecar_init.adoc
  vocab.txt
Labels: okay to merge

#117 MAISTRA-1325: Fix broken OKD links
  topics/docs/comparison-with-istio/ior.adoc
Labels: okay to merge

#116 [Maistra-125] Added Release notes
  topics/contribute/index.adoc
  topics/docs/installation/release-notes.adoc
Labels: okay to merge

#123 Test Prow and Fix Revealed Errors
  .vale.ini
  Makefile
  README.md
  themes/hugo-theme-learn-master/layouts/404.html
  tools/checkLinks.sh
  tools/runLinter.sh
  topics/contribute/index.adoc
  topics/docs/comparison-with-istio/_index.adoc
  topics/docs/comparison-with-istio/ior.adoc
  topics/docs/examples/bookinfo.adoc
  topics/docs/examples/mesh-wide_mtls.adoc
  topics/docs/examples/mesh-wide_rbac.adoc
  topics/docs/installation/311-nodes.adoc
  topics/docs/installation/automatic-injection.adoc
  topics/docs/installation/controlplane.adoc
  topics/docs/installation/installation-options.adoc
  topics/docs/installation/operator-installation.adoc
  topics/docs/installation/release-notes.adoc
  topics/docs/monitoring_and_tracing/grafana.adoc
  topics/docs/monitoring_and_tracing/jaeger-tracing.adoc
  topics/docs/monitoring_and_tracing/kiali.adoc
  topics/docs/monitoring_and_tracing/prometheus.adoc
  topics/docs/monitoring_and_tracing/using-existing-jaeger.adoc
  topics/docs/troubleshooting/deprecated-fields.adoc
  topics/docs/troubleshooting/must_gather.adoc
  topics/docs/troubleshooting/troubleshooting_policy.adoc
  topics/docs/troubleshooting/troubleshooting_sidecar_init.adoc
  topics/snippets/before_you_begin_bookinfo.adoc
  topics/snippets/install_notices.adoc
  vocab.txt
Labels: okay to merge

#125 [cherry-pick to 1.1] Test prow and fix stuff
  .vale.ini
  Makefile
  README.md
  themes/hugo-theme-learn-master/layouts/404.html
  tools/checkLinks.sh
  tools/runLinter.sh
  topics/contribute/index.adoc
  topics/docs/comparison-with-istio/_index.adoc
  topics/docs/comparison-with-istio/ior.adoc
  topics/docs/examples/bookinfo.adoc
  topics/docs/examples/mesh-wide_mtls.adoc
  topics/docs/examples/mesh-wide_rbac.adoc
  topics/docs/installation/311-nodes.adoc
  topics/docs/installation/automatic-injection.adoc
  topics/docs/installation/controlplane.adoc
  topics/docs/installation/installation-options.adoc
  topics/docs/installation/operator-installation.adoc
  topics/docs/installation/release-notes.adoc
  topics/docs/monitoring_and_tracing/grafana.adoc
  topics/docs/monitoring_and_tracing/jaeger-tracing.adoc
  topics/docs/monitoring_and_tracing/kiali.adoc
  topics/docs/monitoring_and_tracing/prometheus.adoc
  topics/docs/monitoring_and_tracing/using-existing-jaeger.adoc
  topics/docs/troubleshooting/deprecated-fields.adoc
  topics/docs/troubleshooting/must_gather.adoc
  topics/docs/troubleshooting/troubleshooting_policy.adoc
  topics/docs/troubleshooting/troubleshooting_sidecar_init.adoc
  topics/snippets/before_you_begin_bookinfo.adoc
  topics/snippets/install_notices.adoc
  vocab.txt
Labels: okay to merge

#126 Fix edit link
  themes/hugo-theme-learn-master/layouts/partials/header.html
Labels: okay to merge, size/XS

#127 Fix edit link
  themes/hugo-theme-learn-master/layouts/partials/header.html
Labels: okay to merge, size/XS

#121 MAISTRA-1219 Use Maistra/istio/samples/bookinfo instead of Maistra/bookinfo
  topics/docs/examples/bookinfo.adoc
Labels: okay to merge, size/S

#128 MAISTRA-1219 Use Maistra/istio/samples/bookinfo instead of Maistra/bookinfo
  topics/docs/examples/bookinfo.adoc
Labels: okay to merge, size/S

#129 Added shortcodes for maistraBranch and maistraVersion
  themes/hugo-theme-learn-master/layouts/shortcodes/maistraBranch.html
  themes/hugo-theme-learn-master/layouts/shortcodes/maistraVersion.html
  topics/docs/examples/bookinfo.adoc
Labels: okay to merge, size/M

#130 Add maistra branch maistra version shortcode
  themes/hugo-theme-learn-master/layouts/shortcodes/maistraBranch.html
  themes/hugo-theme-learn-master/layouts/shortcodes/maistraVersion.html
  topics/docs/examples/bookinfo.adoc
Labels: okay to merge, size/M

#132 Updated PHONY to have the command on a separate line
  Makefile
Labels: okay to merge, size/S

#133 Add kiali install options
  Makefile
  README.adoc
  config.toml
  data/release.yaml
  themes/hugo-theme-learn-master/layouts/partials/menu.html
  tools/checkLinks.sh
  tools/runLinter.sh
  tools/updateFields.sh
  topics/docs/installation/installation-options.adoc
  topics/snippets/istio_installation_smm.adoc
  vars.adoc
  vocab.txt
Labels: okay to merge, size/L
