Repository maistra/maistra.github.io, pull requests merged in 2020-06, with the labels that each got.

#147 Remove 3.11
  topics/docs/installation/311-nodes.adoc
  topics/docs/installation/_index.adoc
  topics/docs/installation/add-redhat-registry.adoc
Labels: cherrypick/maistra-1.1, okay to merge, size/M

#150 This PR does a number of things:
  Makefile
  README.adoc
  data/release.yaml
  data/releases/1.0.8.yaml
  data/releases/1.1.0.yaml
  data/releases/1.1.1.yaml
  layouts/partials/maistraBranch.html
  layouts/shortcodes/maistraBranch.html
  layouts/shortcodes/maistraVersion.html
  layouts/shortcodes/release-notes-table.html
  layouts/shortcodes/snippet_markdown.html
  netlify.toml
  themes/hugo-theme-learn-master/layouts/partials/header.html
  themes/hugo-theme-learn-master/layouts/shortcodes/maistraBranch.html
  themes/hugo-theme-learn-master/layouts/shortcodes/notice.html
  tools/check-git-status.sh
  tools/updateFields.sh
  topics/_index.en.md
  topics/docs/installation/_index.adoc
  topics/docs/installation/installation-options.adoc
  topics/docs/installation/operator-installation.adoc
  topics/docs/installation/release-notes.adoc
  topics/index.md
  vars.adoc
Labels: okay to merge, size/L

#145 Document the version field
  data/release.yaml
  data/releases/1.1.1.yaml
  layouts/partials/maistraOperatorInstallableVersions.html
  layouts/partials/maistraOperatorVersion.html
  layouts/shortcodes/maistraOperatorInstallableVersions.html
  layouts/shortcodes/maistraOperatorVersion.html
  topics/docs/installation/installation-options.adoc
Labels: okay to merge, size/S

#151 Document the version field
  data/releases/1.1.1.yaml
  data/releases/1.2.0.yaml
  layouts/partials/maistraOperatorInstallableVersions.html
  layouts/partials/maistraOperatorVersion.html
  layouts/shortcodes/maistraOperatorInstallableVersions.html
  layouts/shortcodes/maistraOperatorVersion.html
  topics/docs/installation/installation-options.adoc
Labels: okay to merge, size/XS

#154 MAISTRA-1558 add docs for removing cert-manager CRDs
  topics/docs/installation/release-notes.adoc
Labels: okay to merge, size/S
