Repository maistra/maistra.github.io, pull requests merged in 2020-05, with the labels that each got.

#135 added license
  LICENSE
Labels: okay to merge, size/L

#138 Added release notes for maistra-1.1.1
  topics/docs/installation/release-notes.adoc
Labels: okay to merge, size/S

#143 MAISTRA-1466 Fix the apiVersion fields in example resources
  topics/docs/examples/mesh-wide_mtls.adoc
  topics/docs/examples/mesh-wide_rbac.adoc
Labels: cherrypick/maistra-1.1, okay to merge, size/XS

#139 Release table
  Makefile
  README.adoc
  data/release.yaml
  data/releases/1.0.8.yaml
  data/releases/1.1.0.yaml
  data/releases/1.1.1.yaml
  data/releases/1.2.0.yaml
  layouts/partials/maistraBranch.html
  layouts/shortcodes/maistraBranch.html
  layouts/shortcodes/maistraVersion.html
  layouts/shortcodes/release-notes-table.html
  layouts/shortcodes/snippet_markdown.html
  netlify.toml
  themes/hugo-theme-learn-master/layouts/partials/header.html
  themes/hugo-theme-learn-master/layouts/shortcodes/maistraBranch.html
  themes/hugo-theme-learn-master/layouts/shortcodes/notice.html
  tools/check-git-status.sh
  tools/updateFields.sh
  topics/_index.en.md
  topics/docs/installation/_index.adoc
  topics/docs/installation/installation-options.adoc
  topics/docs/installation/operator-installation.adoc
  topics/docs/installation/release-notes.adoc
  topics/index.md
Labels: okay to merge, size/L
