Repository maistra/maistra.github.io, pull requests merged in 2020-10, with the labels that each got.

#167 [MAISTRA-1892] Fix broken links and add dependency to 'yq' in the README
  README.adoc
  vocab.txt
Labels: ok-to-test, okay to merge, size/S

#169 Update config.toml
  config.toml
Labels: okay to merge, size/XS

#170 MAISTRA-1871 Mention the blank page issue when creating SMCP via web console
  topics/docs/installation/controlplane.adoc
Labels: okay to merge, size/XS

#168 MAISTRA-1822 Add documentation for WebAssembly Extensions
  topics/docs/wasm-extensions/_index.adoc
  topics/docs/wasm-extensions/building_extensions.adoc
  topics/docs/wasm-extensions/using_extensions.adoc
  vocab.txt
Labels: okay to merge, size/L
