Repository maistra/maistra.github.io, pull requests merged in 2021-01, with the labels that each got.

#174 Fix yq usage and broken links
  tools/check-yq.sh
  tools/checkLinks.sh
  tools/updateFields.sh
  topics/docs/comparison-with-istio/_index.adoc
Labels: okay to merge, size/M

#173 MAISTRA-2060: Point to Red Hat Jira for issues
  .github/ISSUE_TEMPLATE/config.yml
  README.adoc
Labels: okay to merge, size/XS

#163 Added feature to run Maistra web site in a local container.
  Makefile
  README.adoc
  vocab.txt
Labels: ok-to-test, okay to merge, size/M
